In [1]:
import pandas as pd
import numpy as np
from src.funct import sum_and_round, mean_and_round, plot_boxplot_with_points, mquintile, plot_q25


import matplotlib.pyplot as plt
import seaborn as sns

import altair as alt
from altair import datum #Needed for subsetting (transforming data)

# IQR, Lower and Upper Whiskers, Outliers

## Interquartile range IQR

The **interquaritle range (IQR)** is a measure of statistical dispersion which means it is an indicator about how the data are spread. It is defined as the difference between the third and first quartile (or the 75<sup>th</sup> and 25<sup>th</sup> percentile) and so, by definition, it contains $50/%$ of the data.

In [2]:
data = pd.read_excel('./data/superstore_data.xlsx')

In [3]:
data.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

In [4]:
data['Region'].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

In [5]:
df_subcategory = (data
 .groupby(['Region', 'Sub-Category'])
 .agg(
     Sales = ('Sales', sum_and_round),
     Profit = ('Profit', sum_and_round),
     Quantity = ('Quantity', sum_and_round),
     Discount = ('Discount', mean_and_round)
 )
 .reset_index()
)

In [6]:
df_subcategory.head()

    Region Sub-Category    Sales  Profit  Quantity  Discount
0  Central  Accessories  33956.0  7252.0       716    0.1246
1  Central   Appliances  23582.0 -2639.0       470    0.4488
2  Central          Art   5765.0  1195.0       678    0.1227
3  Central      Binders  56923.0 -1044.0      1473    0.5093
4  Central    Bookcases  24157.0 -1998.0       192    0.2328

In [7]:
obs = 'Profit'

box = (alt
       .Chart(df_subcategory)
       .mark_boxplot(size = 25, color = 'silver')
       .encode(
           x = alt.X('Profit:Q'),
           y = 'Region'
       )
      )

box.properties(
    title = 'Sales by Sub-category box plot',
    width = 620,
    height = 150
)

alt.Chart(...)

In [8]:
df_south_profit = df_subcategory[df_subcategory['Region'] == 'South'][['Region', 'Sub-Category', 'Profit']]
df_south_profit.head(4)

   Region Sub-Category  Profit
34  South  Accessories  7005.0
35  South   Appliances  4124.0
36  South          Art  1059.0
37  South      Binders  3901.0

In [9]:
plot_boxplot_with_points(df_south_profit, 'Sub-Category', 'Profit')

alt.LayerChart(...)

In [10]:
mquintile(df_south_profit['Profit'], 0.25)

Whole number
1041.0

1041.0

In [11]:
mquintile(df_south_profit['Profit'], 0.75)

Whole number
4124.0

4124.0

In [12]:
np.quantile(df_south_profit['Profit'], q=0.25)

1041.0

In [13]:
np.quantile(df_south_profit['Profit'], q=0.75)

4124.0

In [14]:
IQR = np.quantile(df_south_profit['Profit'], q=0.75) - np.quantile(df_south_profit['Profit'], q=0.25)
IQR

3083.0

In [15]:
df_south_profit[(df_south_profit['Profit'] >= mquintile(df_south_profit['Profit'], 0.25)) & (df_south_profit['Profit'] <= mquintile(df_south_profit['Profit'], 0.75))].shape

Whole number
1041.0
Whole number
4124.0

(9, 3)

In [16]:
df_south_profit.shape

(17, 3)

In [17]:
lower_whisker = np.quantile(df_south_profit['Profit'], q=0.25) - (1.5*IQR)
lower_whisker

-3583.5

In [18]:
upper_whisker = np.quantile(df_south_profit['Profit'], q=0.75) + (1.5*IQR)
upper_whisker

8748.5

In [19]:
df_south_profit['Profit'][df_south_profit['Profit'].sort_values() > lower_whisker].min()

-1439.0

In [20]:
df_south_profit['Profit'][df_south_profit['Profit'].sort_values() < upper_whisker].max()

7005.0

In [21]:
test = np.array([7,7,31,31,47,75,87,115,116,119,119,155,177])
df_test = pd.DataFrame(
    {
        'index' : np.arange(1, len(test)+1),
        'x' : test
    }
)

In [22]:
np.median(test)

87.0

In [23]:
np.quantile(test, 0.25)

31.0

In [24]:
np.quantile(test, 0.75)

119.0

In [25]:
plot_boxplot_with_points(df_test, 'index','x')

alt.LayerChart(...)

In [26]:
IQR = np.quantile(test, 0.75) - np.quantile(test, 0.25)
IQR

88.0

In [27]:
119-31

88

In [28]:
lower_whisker = np.quantile(test, 0.25) - 1.5*IQR
lower_whisker

-101.0

In [29]:
df_test

    index    x
0       1    7
1       2    7
2       3   31
3       4   31
4       5   47
5       6   75
6       7   87
7       8  115
8       9  116
9      10  119
10     11  119
11     12  155
12     13  177

In [30]:
lower_whisker = np.quantile(test, q=0.25) - (1.5*IQR)
df_test['x'][df_test['x'].sort_values() > lower_whisker].min()

7

In [31]:
upper_whisker = np.quantile(test, q = 0.25) + (1.5*IQR)
df_test['x'][df_test['x'].sort_values() > upper_whisker].max()

177